name: quaketrack
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.1
  provider: ^6.1.2
  go_router: ^13.2.0
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.19
  flutter_local_notifications: ^17.0.0
  cloud_firestore: ^4.15.8
  shared_preferences: ^2.2.2
  geolocator: ^11.0.0
  firebase_auth: ^4.17.8
  google_sign_in: ^6.2.1
  url_launcher: ^6.3.0
  intl: ^0.19.0
  google_maps_flutter: ^2.6.1
  firebase_crashlytics: ^3.5.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Oswald
      fonts:
        - asset: fonts/Oswald-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
          weight: 400
