name: quaketrack
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.1
  provider: ^6.1.2
  go_router: ^17.1.0
  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1
  flutter_local_notifications: ^20.1.0
  cloud_firestore: ^6.1.2
  shared_preferences: ^2.2.2
  geolocator: ^14.0.2
  firebase_auth: ^6.1.4
  google_sign_in: ^6.3.0
  url_launcher: ^6.3.0
  intl: ^0.20.2
  flutter_map: ^8.2.2 # Reverted to previous working version
  firebase_crashlytics: ^5.0.7
  rxdart: ^0.28.0
  latlong2: ^0.9.1 # Reverted to original, will let flutter_map update its dependency
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.4.3
  dart_geohash: ^2.1.0
  introduction_screen: ^4.0.0
  web_socket_channel: ^3.0.3
  share_plus: ^12.0.1
  screenshot: ^3.0.0
  path_provider: ^2.1.2 # Added for temporary file storage
  cross_file: ^0.3.4 # Added for XFile
  google_mobile_ads: ^7.0.0
  uuid: ^4.0.0 # Added for generating unique IDs
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.11
  hive_generator: ^2.0.1

  flutter_lints: ^6.0.0
  analyzer: ^6.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Oswald
      fonts:
        - asset: fonts/Oswald-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
          weight: 400
